#include "model.h"
#include "atom.h"
#include "controller.h"
#include "misc.h"
#include "container3d.h"
#include <string>
#include <vector>
#include <iostream>
#include <fstream>
#include <filesystem>

///////////////////////////////
// AUX FUNCTION DECLARATIONS //
///////////////////////////////

std::string timeNow();

///////////////////
// RESULT REPORT //
///////////////////

//
bool Model::createOutputFolder(){
  // folder name based on current time to avoid overwriting output files with successive calculations
  output_folder = "./output/" + timeNow();
  if(std::filesystem::create_directories(output_folder)){
    return true;
  }
  else{
    output_folder = "./";
    return false;
  }
}

void Model::createReport(std::string input_filepath, std::vector<std::string> parameters){
  std::ofstream output_report(output_folder+"/MoloVol result report.txt");
  output_report << "MoloVol program: calculation results report\n\n";
  output_report << "Structure file analyzed: " << input_filepath << "\n";
  for(int i = 0; i < parameters.size(); i++){
    output_report << parameters[i] << "\n";
  }
  output_report.close();
}

//////////////////////
// STRUCTURE OUTPUT //
//////////////////////

void Model::writeXYZfile(std::vector<std::tuple<std::string, double, double, double>> &atom_coordinates, std::string output_type){
  std::ofstream output_structure(output_folder+"/structure_"+output_type+".xyz");
  output_structure << output_type << "\nStructure generated with MoloVol\n\n";
  for(int i = 0; i < atom_coordinates.size(); i++){
    output_structure << std::get<0>(atom_coordinates[i]) << " ";
    output_structure << std::to_string(std::get<1>(atom_coordinates[i])) << " ";
    output_structure << std::to_string(std::get<2>(atom_coordinates[i])) << " ";
    output_structure << std::to_string(std::get<3>(atom_coordinates[i])) << "\n";
  }
  output_structure.close();
}

////////////////////////
// SURFACE MAP OUTPUT //
////////////////////////

void Model::writeSurfaceMap(std::string output_dir){
  
  // assemble data
  Container3D<char> surface_map = _cell.generateTypeTensor();
  // save commonly used variable
  std::array<unsigned long int,3> n_elements = surface_map.getNumElements();
  double vxl_length = _cell.getResolution();
  // create map for assigning numbers to types
  std::map<char,int> typeToNum = 
    {{0b00000011, 0},
     {0b00000101, 2},
     {0b00001001, 6},
     {0b00010001, 4},
     {0b00100001, 8},
     {0b01000001, 3.3}};

  // user must enter a valid directory to output the file
  std::cout << (output_dir + "/surface_map.dx") << std::endl;
  // create and open new file
  std::ofstream output_file;
  output_file.open(output_dir + "/surface_map.dx");
  // comments
  output_file << "# OpenDX density file generated by MoloVol\n";
  output_file << "# Contains 3D surface map data to read in PyMol or Chimera\n";
  output_file << "# Data is written in C array order: In grid[x,y,z] the axis x is fastest\n";
  output_file << "# varying, then y, then finally z.\n";
  // line
  output_file << "object 1 class gridpositions counts";
  for (char i = 0; i < 3; i++){
    output_file << ' ' << n_elements[i];
  }
  output_file << "\n";
  // line
  output_file << "origin ";
  for (char i = 0; i < 3; i++){
    output_file << ' ' << _cell.getMin()[i] + vxl_length/2;
  }
  output_file << '\n';
  // 3 lines
  for (char i = 0; i < 3; i++){
    output_file << "delta";
    for (char j = 0; j < 3; j++){
      output_file << ' ' << ((i==j)? vxl_length : 0);
    }
    output_file << '\n';
  }
  // line
  output_file << "object 2 class gridconnections counts";
  for (char i = 0; i < 3; i++){
    output_file << ' ' << n_elements[i];
  }
  output_file << '\n';
  // line
  output_file << "object 3 class array type float rank 0 items " << _cell.totalVxlOnLvl(0) << "\n";
  // data
  int column = 0;
  for(size_t x = 0; x < n_elements[0]; x++){
    for(size_t y = 0; y < n_elements[1]; y++){
      for(size_t z = 0; z < n_elements[2]; z++){
        if (typeToNum.count(surface_map.getElement(x,y,z)) != 0){
          output_file << typeToNum[surface_map.getElement(x,y,z)];
        }
        else {
          output_file << -2;
        }
        output_file << ((column == 2)? '\n' : ' ');
        column = (column+1)%3;
      }
    }
  }
  if (column != 0) {
    output_file << '\n';
  }
  output_file << "attribute \"dep\" string \"positions\"\n";
  output_file << "object \"density\" class field\n";
  output_file << "component \"positions\" value 1\n";
  output_file << "component \"connections\" value 2\n";
  output_file << "component \"data\" value 3";

  // close the file
  output_file.close();
}

///////////////////
// AUX FUNCTIONS //
///////////////////

// find the current time and convert to a string in format year-month-day_hour-min-sec
std::string timeNow(){
    time_t rawtime;
    struct tm * timeinfo;
    char buffer[80];

    time (&rawtime);
    timeinfo = localtime (&rawtime);

    strftime (buffer,80,"%Y-%m-%d_%Hh%Mm%Ss",timeinfo);

    return buffer;
}




