
# XCode compatibility
set_target_properties(${EXE_NAME} PROPERTIES
  XCODE_GENERATE_SCHEME TRUE
  XCODE_SCHEME_WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
)

# macOS Bundle
set_target_properties(${EXE_NAME} PROPERTIES
  MACOSX_BUNDLE_BUNDLE_NAME ${EXE_NAME}
  MACOSX_BUNDLE_EXECUTABLE_NAME ${EXE_NAME}
  MACOSX_BUNDLE_BUNDLE_VERSION ${CMAKE_PROJECT_VERSION}
  MACOSX_BUNDLE_ICON_FILE icon
)

