set(CPACK_PACKAGE_NAME ${EXE_NAME})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY 
  "Scientific software for molecular volumes and surface areas\nProvides calculation and surface map exports.")
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_CONTACT "molovol@outlook.com")
set(CPACK_PACKAGE_VENDOR "MoloVol")
set(CPACK_RESOURCE_FILE_README ${README_FILE})

if (APPLE)
  set(CPACK_RESOURCE_FILE_LICENSE ${OSX_LICENSE_RTF})
elseif (MSVC)
  set(CPACK_RESOURCE_FILE_LICENSE ${WIN_LICENSE_RTF})
else()
  set(CPACK_RESOURCE_FILE_LICENSE ${LICENSE_FILE})
endif()

set(CPACK_DEBIAN_PACKAGE_SECTION "science")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Jasmin B. Maglic <${CPACK_PACKAGE_CONTACT}>")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${LINUX_ARCHITECTURE})
set(CPACK_DEBIAN_FILE_NAME 
  ${PROJECT_NAME}_debian_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}_v${CPACK_PACKAGE_VERSION}.deb)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

set(CPACK_DMG_VOLUME_NAME ${PROJECT_NAME})
set(CPACK_DMG_BACKGROUND_IMAGE ${OSX_DMG_BACKGROUND})
set(CPACK_DMG_DS_STORE ${OSX_DMG_DSSTORE})

if (MSVC)
  #include(InstallRequiredSystemLibraries)
  set(CPACK_GENERATOR "ZIP;NSIS")
  set(CPACK_NSIS_MODIFY_PATH "ON")

  set(CPACK_CREATE_DESKTOP_LINKS ${EXE_NAME})
  set(CPACK_PACKAGE_EXECUTABLES ${EXE_NAME};MoloVol)
  set(CPACK_NSIS_INSTALLED_ICON_NAME bin/${EXE_NAME}.exe)

  install(TARGETS ${EXE_NAME} DESTINATION bin)
  #install(FILES $<TARGET_RUNTIME_DLLS:${EXE_NAME}> TYPE BIN)
  install(FILES ${README_FILE} DESTINATION . RENAME README.txt)
  install(FILES ${LICENSE_FILE} DESTINATION . RENAME LICENSE.txt)
  install(FILES ${ELEM_FILE} ${SPACEGROUP_FILE} DESTINATION shared/inputfile)
  install(FILES ${TPL_VTK} DESTINATION legal RENAME VTK.txt)

  install(FILES ${EXAMPLE_FILES} DESTINATION shared/example)

endif()

include(CPack)
