# Generated by VTKModulesForCxx.py
set(VTK_DIR ${CMAKE_SOURCE_DIR}/external/VTK-9.3.0/build_arm64)
find_package(VTK
 COMPONENTS
    CommonColor
    CommonCore
    CommonDataModel
    FiltersCore
    FiltersSources
    IOImage
    ImagingHybrid
    InteractionWidgets
    RenderingCore
    RenderingVolumeOpenGL2
    #
    # These modules are suggested since they implement an existing module.
    # You may need to uncomment one or more of these.
    # If vtkRenderWindow is used and you want to use OpenGL,
    #   you also need the RenderingOpenGL2 module.
    # If vtkRenderWindowInteractor is used,
    #    uncomment RenderingUI and possibly InteractionStyle.
    # If text rendering is used, uncomment RenderingFreeType
    #
    # FiltersParallel   # implements VTK::FiltersCore
    InteractionStyle  # implements VTK::RenderingCore
    # RenderingCellGrid # implements VTK::RenderingCore
    # RenderingFreeType # implements VTK::RenderingCore
    RenderingOpenGL2  # implements VTK::RenderingCore
    RenderingUI       # implements VTK::RenderingCore
)

# wxVTKRenderWindowInteractor library
set(WXVTK_LIB wxVTK24)
set(WXVTK_SRC_DIR ${CMAKE_SOURCE_DIR}/external/WxVTK_CPP_Random_Cube_Visualized)
include_directories(${WXVTK_SRC_DIR})
add_library(${WXVTK_LIB}
  STATIC ${WXVTK_SRC_DIR}/wxVTKRenderWindowInteractor.cxx 
  ${WXVTK_SRC_DIR}/wxVTKRenderWindowInteractor.h)
target_link_libraries(${WXVTK_LIB} ${VTK_LIBRARIES} ${wxWidgets_LIBRARIES})

vtk_module_autoinit(
  TARGETS ${WXVTK_LIB}
  MODULES ${VTK_LIBRARIES}
)
